/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "A30IuIjQYYg",
    title: "Thailand - Cinematic Travel",
    description: "Land of incredible stories.",
    creator: "Benn TK",
    categoryName: "country",
    views: "290",
    releaseDate: "Aug 28 2018",
  },
  {
    _id: "DIgv-e18OzA",
    title: "Vietnam - Cinematic Travel",
    description: "Land of ancient secrets",
    creator: "Benn TK",
    categoryName: "city",
    views: "110",
    releaseDate: "Sept 12 2021",
  },
  {
    _id: "oM_9lF4u4_o",
    title: "Kedarnath Yatra 2020",
    description: "Sonprayag to Kedarnath Temple, 16km Trekking",
    creator: "Naveen Rawat",
    categoryName: "state",
    views: "1",
    releaseDate: "Nov 10 2011",
  },
  {
    _id: "ssYuPTdMt8A",
    title: "Visit in Gibhi",
    description: "10 Beautiful Tourist categoryNames to Visit in Jibhi",
    creator: "Walking wanderer",
    categoryName: "village",
    views: "2",
    releaseDate: "Dec 19 2013",
  },
  {
    _id: "2YlOJiEUVOY&t=5s",
    title: "Tirthan Valley",
    description: "Travel Guide 2020 | Trek",
    creator: "Abhimanyu Dalal",
    categoryName: "town",
    views: "210",
    releaseDate: "Dec 9 2017",
  },
  {
    _id: "AotsXapzQyU",
    title: "Shimla Kufri",
    description: "Travel to Kufri",
    creator: "Modern banjare",
    categoryName: "city",
    views: "230",
    releaseDate: "Apr 13 2012",
  },
  {
    _id: "hn6-k3bLcaE",
    title: "KOLKATA - FROM THE SKY",
    description: "DRONE FOOTAGE || DJI MAVIC MINI",
    creator: "Take a tour",
    categoryName: "city",
    views: "4",
    releaseDate: "Jan 28 2017",
  },
  {
    _id: "vydEu1I9r5c",
    title: "Ladakh",
    description: "Pangong Lake | Nubra Valley",
    creator: "Garima's good life",
    categoryName: "union territory",
    views: "4",
    releaseDate: "Jan 14 2010",
  },
  {
    _id: "qi52KQs67MY",
    title: "Philippines",
    description: "Land of enchanted Islands | Epic Travel Cinematic",
    creator: "Benn TK",
    categoryName: "country",
    views: "10",
    releaseDate: "Mar 24 2015",
  },];
